-- #216: 日次Codex収集の分類・地域・検索実績を保存し、画面で検証できるようにする。
ALTER TABLE `industry_information`
  MODIFY COLUMN `informationType` ENUM('NEW_PRODUCT', 'COMPETITOR', 'INTRODUCTION_CASE', 'RECRUITMENT_PARTNERSHIP', 'POLICY_SUBSIDY', 'MARKET_STATISTICS', 'USER_ISSUE', 'CONSTRUCTION', 'QUALITY_SAFETY', 'PATENT', 'ACADEMIC_RESEARCH', 'VIDEO', 'SOCIAL_TREND', 'OVERSEAS_CASE', 'OTHER') NOT NULL,
  ADD COLUMN `region` VARCHAR(191) NULL;

ALTER TABLE `collection_search_jobs`
  ADD COLUMN `searchReport` JSON NULL;
